### ISSUE TITLE
Module not found on yarn dev

### ISSUE THREAD

**Issue by equinusocio** [contactlab/yeoman-generators#8]
> { Error: Cannot find module './build/Release/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/******/******/******/******/******/pro-backend-contactone/node_modules/dtrace-provider/dtrace-provider.js:18:23)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3) code: 'MODULE_NOT_FOUND' }

When run `yarn dev`. This is not a blocking issue.

**Comment by StefanoMagrassi** [comment]
@equinusocio is this issue still open?

**Comment by equinusocio** [comment]
Yes. But this occurs only on mac

**Comment by StefanoMagrassi** [comment]
@equinusocio this issue is related to [contactlab-ui-components #164](https://github.com/contactlab/contactlab-ui-components/issues/164 )?

**Comment by equinusocio** [comment]
no, it is not related.
